fix: temporarily comment rollback and add todo for fixing signing (#6)

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -137,6 +137,7 @@ jobs:
       # repository is public to avoid leaking data.  If you would like to publish
       # transparency data even for private images, pass --force to cosign below.
       # https://github.com/sigstore/cosign
+    #   TODO: fix
       - name: Sign the published Docker image
         if: ${{ github.event_name != 'pull_request' }}
         env:
@@ -147,18 +148,18 @@ jobs:
         # against the sigstore community Fulcio instance.
         run: cosign sign --yes "${TAGS}@${DIGEST}"
 
-      - name: Rollback Release
-        if: ${{ (cancelled() || failure()) && github.event_name == 'release' }}
-        uses: author/action-rollback@stable
-        with:
-          tag: ${{ github.ref }}
-          delete_orphan_tag: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #   - name: Rollback Release
+    #     if: ${{ (cancelled() || failure()) && github.event_name == 'release' }}
+    #     uses: author/action-rollback@stable
+    #     with:
+    #       tag: ${{ github.ref }}
+    #       delete_orphan_tag: true
+    #     env:
+    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Cleanup Failed Docker Container
-        if: ${{ (cancelled() || failure()) && github.event_name == 'release' }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          VERSION: ${{ steps.meta.outputs.version }}
-        run: docker rmi --force "${ IMAGE_NAME }:${ VERSION }"
+    #   - name: Cleanup Failed Docker Container
+    #     if: ${{ (cancelled() || failure()) && github.event_name == 'release' }}
+    #     env:
+    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #       VERSION: ${{ steps.meta.outputs.version }}
+    #     run: docker rmi --force "${ IMAGE_NAME }:${ VERSION }"
